EzLib/Controllers/BorrowReturnLibraryItemController.cs
using EzLib.Data;
using EzLib.Models;
using EzLib.Services.Services;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace EzLib.Controllers
{
    public class BorrowReturnLibraryItemController : Controller
    {
        private readonly EzLibContext _context;
        private readonly IAcronymGeneratorService _acronymGeneratorService;
        private readonly ILibraryItemsService _libraryItemsService;
        private readonly IBorrowReturnLibraryItemService _borrowReturnLibraryItemService;

        // Constructor that injects EzLibContext, IAcronymGeneratorService, ILibraryItemsService, and IBorrowReturnLibraryItemService dependencies
        public BorrowReturnLibraryItemController(EzLibContext context, IAcronymGeneratorService acronymGeneratorService, ILibraryItemsService libraryItemsService, IBorrowReturnLibraryItemService borrowReturnLibraryItemService)
        {
            _context = context;
            _acronymGeneratorService = acronymGeneratorService;
            _libraryItemsService = libraryItemsService;
            _borrowReturnLibraryItemService = borrowReturnLibraryItemService;
        }

        // GET: LibraryItems/Borrow/5
        [HttpGet]
        public async Task<IActionResult> Borrow(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libraryItem = await _borrowReturnLibraryItemService.GetBorrowableLibraryItemAsync(id.Value);

            if (libraryItem == null)
            {
                return NotFound();
            }

            string acronym = _acronymGeneratorService.GenerateAcronym(libraryItem.Title);
            libraryItem.Title = $"{acronym}";

            // Populate any necessary data for the view (e.g., ViewBag)

            return View(libraryItem);
        }

        [HttpPost, ActionName("Borrow")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BorrowConfirmed(int id, string borrower)
        {
            // Create a temporary LibraryItem object to validate the borrower string
            var tempLibraryItem = new LibraryItem { Borrower = borrower };

            // Validate the Borrower property using Data Annotations
            var validationResults = new List<ValidationResult>();
            var validationContext = new ValidationContext(tempLibraryItem) { MemberName = nameof(tempLibraryItem.Borrower) };
            Validator.TryValidateProperty(tempLibraryItem.Borrower, validationContext, validationResults);

            // Add validation errors to the ModelState
            foreach (var validationResult in validationResults)
            {
                ModelState.AddModelError(nameof(borrower), validationResult.ErrorMessage);
            }

            if (ModelState.IsValid)
            {
                var result = await _borrowReturnLibraryItemService.BorrowConfirmed(id, borrower);

                if (!result)
                {
                    return NotFound();
                }

                // Handle the redirection or view rendering after successful borrowing
                return RedirectToAction("Index", "LibraryItems");
            }
            else
            {
                // Populate the necessary data for the view and return the Borrow view with the current model
                var libraryItem = await _borrowReturnLibraryItemService.GetBorrowableLibraryItemAsync(id);
                if (libraryItem == null)
                {
                    return NotFound();
                }
                return View("Borrow", libraryItem);
            }
        }


        // GET: LibraryItems/Return/5
        [HttpGet]
        public async Task<IActionResult> Return(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libraryItem = await _borrowReturnLibraryItemService.GetReturnableLibraryItemAsync(id.Value);

            if (libraryItem == null || string.IsNullOrEmpty(libraryItem.Borrower))
            {
                return NotFound();
            }

            // Populate any necessary data for the view (e.g., ViewBag)

            return View(libraryItem);
        }

        [HttpPost, ActionName("Return")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ReturnConfirmed(int id, string submit)
        {
            // Confirm the return of the library item
            bool isConfirmed = await _borrowReturnLibraryItemService.ConfirmReturnAsync(id);

            if (!isConfirmed)
            {
                return NotFound();
            }

            // Determine the action to take based on the value of the 'submit' parameter
            if (submit == "yes")
            {
                // Redirect to the Index action of the LibraryItems controller
                return RedirectToAction("Index", "LibraryItems");
            }
            else
            {
                // Redirect to the Index action of the current controller
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

EzLib/Controllers/LibraryItemsController.cs
using EzLib.Data;
using EzLib.Models;
using EzLib.Services.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EzLib.Controllers
{
    public class LibraryItemsController : Controller
    {
        private readonly EzLibContext _context;
        private readonly IAcronymGeneratorService _acronymGeneratorService;
        private readonly ILibraryItemsService _libraryItemsService;
        private readonly IBorrowReturnLibraryItemService _borrowReturnLibraryItemService;
        private readonly ILibraryItemValidationService _libraryItemValidationService;
        private readonly IBlockedFieldClearingService _blockedFieldClearingService;

        public LibraryItemsController(EzLibContext context, IAcronymGeneratorService acronymGeneratorService, ILibraryItemsService libraryItemsService, IBorrowReturnLibraryItemService borrowReturnLibraryItemService, ILibraryItemValidationService libraryItemValidationService,
            IBlockedFieldClearingService blockedFieldClearingService)
        {
            _context = context;
            _acronymGeneratorService = acronymGeneratorService;
            _libraryItemsService = libraryItemsService;
            _borrowReturnLibraryItemService = borrowReturnLibraryItemService;
            _libraryItemValidationService = libraryItemValidationService;
            _blockedFieldClearingService = blockedFieldClearingService;
        }

        // GET: LibraryItems
        public async Task<IActionResult> Index(string sortByType = null, string searchString = null)
        {
            // Check if sortByType parameter is provided
            if (!string.IsNullOrEmpty(sortByType))
            {
                // Store sortByType value in session
                HttpContext.Session.SetString("sortByType", sortByType);
            }
            else if (HttpContext.Session.GetString("sortByType") != null)
            {
                // Retrieve sortByType value from session
                sortByType = HttpContext.Session.GetString("sortByType");
            }

            // Get library items based on sortByType and searchString
            var (libraryItems, updatedSortByType) = await _libraryItemsService.GetLibraryItemsAsync(sortByType, searchString);

            return View(libraryItems);
        }

        // GET: LibraryItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            // Retrieve library item details by ID
            var libraryItem = await _libraryItemsService.GetLibraryItemDetailsAsync(id);

            if (libraryItem == null)
            {
                return NotFound();
            }

            return View(libraryItem);
        }

        // GET: LibraryItems/Create
        public IActionResult Create()
        {
            // Populate the CategoryId dropdown list
            ViewData["CategoryId"] = new SelectList(_context.Category, "Id", "CategoryName");
            return View();
        }

        // POST: LibraryItems/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CategoryId,Title,Author,Pages,RunTimeMinutes,IsBorrowable,Type")] LibraryItem libraryItem)
        {
            // Validate the library item
            var validationErrors = _libraryItemValidationService.ValidateLibraryItem(libraryItem);

            // Remove validation errors from ModelState
            foreach (var error in validationErrors)
            {
                ModelState.Remove(error.Key);
            }

            if (ModelState.IsValid)
            {
                // Check if the library item title is unique
                if (!await _libraryItemsService.IsLibraryItemTitleUnique(libraryItem))
                {
                    ModelState.AddModelError(string.Empty, "Title name must be unique.");
                    ViewBag.CategoryId = new SelectList(_context.Category, "Id", "CategoryName", libraryItem.CategoryId);
                    return View(libraryItem);
                }

                // Add the library item and save changes
                _context.Add(libraryItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            // Populate the CategoryId dropdown list
            ViewData["CategoryId"] = new SelectList(_context.Category, "Id", "CategoryName", libraryItem.CategoryId);
            return View(libraryItem);
        }


        // GET: LibraryItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.LibraryItem == null)
            {
                return NotFound();
            }

            var libraryItem = await _libraryItemsService.GetLibraryItemAsync(id);
            if (libraryItem == null)
            {
                return NotFound();
            }

            // Check if the item is not borrowable and the borrower is not empty
            if (!libraryItem.IsBorrowable && !string.IsNullOrEmpty(libraryItem.Borrower))
            {
                return Forbid(); // Return forbidden status or redirect to an unauthorized page
            }

            // Populate the CategoryId dropdown list
            ViewData["CategoryId"] = new SelectList(_context.Category, "Id", "CategoryName");
            return View(libraryItem);
        }

        // POST: LibraryItems/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CategoryId,Title,Author,Pages,RunTimeMinutes,IsBorrowable,Type")] LibraryItem libraryItem)
        {
            if (id != libraryItem.Id)
            {
                return NotFound();
            }

            var validationErrors = _libraryItemValidationService.ValidateLibraryItem(libraryItem);

            // Remove validation errors from ModelState
            foreach (var error in validationErrors)
            {
                ModelState.Remove(error.Key);
            }

            if (ModelState.IsValid)
            {
                // Check if the library item title is unique
                if (!await _libraryItemsService.IsLibraryItemTitleUnique(libraryItem))
                {
                    ModelState.AddModelError("UniqueTitle", "Title name must be unique.");
                    // Populate the SelectList for the Category dropdown before returning the View
                    ViewBag.CategoryId = new SelectList(_context.Category, "Id", "CategoryName", libraryItem.CategoryId);
                    return View(libraryItem);
                }

                // Update the library item
                bool updateResult = await _libraryItemsService.UpdateLibraryItemAsync(id, libraryItem);

                if (!updateResult)
                {
                    return NotFound();
                }

                return RedirectToAction(nameof(Index));
            }

            // Populate the CategoryId dropdown list
            ViewData["CategoryId"] = new SelectList(_context.Category, "Id", "Id", libraryItem.CategoryId);
            return View(libraryItem);
        }

        // GET: LibraryItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var libraryItem = await _libraryItemsService.GetLibraryItemForDeleteAsync(id);

            if (libraryItem == null)
            {
                return NotFound();
            }

            // Check if the item is not borrowable and the borrower is not empty
            if (!libraryItem.IsBorrowable && !string.IsNullOrEmpty(libraryItem.Borrower))
            {
                return Forbid(); // Return forbidden status or redirect to an unauthorized page
            }

            return View(libraryItem);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            bool isDeleted = await _libraryItemsService.DeleteLibraryItemAsync(id);

            if (!isDeleted)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

EzLib/Views/LibraryItems/Create.cshtml
@model EzLib.Models.LibraryItem

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>LibraryItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select id="Type" asp-for="Type" class="form-control">
                    <option value="Book">Book</option>
                    <option value="DVD">DVD</option>
                    <option value="Audio Book">Audio Book</option>
                    <option value="Reference Book">Reference Book</option>
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId">
                    <option value=""> Select</option></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pages" class="control-label"></label>
                <input asp-for="Pages" class="form-control" required 
                    data-val-required="Pages must be between 1 and 10000." />
                <span asp-validation-for="Pages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RunTimeMinutes" class="control-label"></label>
                <input asp-for="RunTimeMinutes" class="form-control" required 
                    data-val-required="RunTimeMinutes must be between 1 and 10000." />
                <span asp-validation-for="RunTimeMinutes" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsBorrowable" /> @Html.DisplayNameFor(model => model.IsBorrowable)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="~/js/validateLibraryItem.js" asp-append-version="true"></script>
    <script src="~/js/resetValidationMessages.js" asp-append-version="true"></script>
}

EzLib/Views/LibraryItems/Delete.cshtml
@model EzLib.Models.LibraryItem

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LibraryItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pages)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pages)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RunTimeMinutes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RunTimeMinutes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsBorrowable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsBorrowable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Borrower)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Borrower)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BorrowDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BorrowDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EzLib/Views/LibraryItems/Details.cshtml
@model EzLib.Models.LibraryItem

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>LibraryItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pages)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pages)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RunTimeMinutes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RunTimeMinutes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsBorrowable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsBorrowable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Borrower)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Borrower)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BorrowDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BorrowDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>
    </dl>
</div>
<div>
    @if (Model.IsBorrowable && (string.IsNullOrEmpty(Model.Borrower) || Model.Type == "Reference Book"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
    }     |
    <a asp-action="Index">Back to List</a>
</div>

EzLib/Views/LibraryItems/Edit.cshtml
@model EzLib.Models.LibraryItem

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>LibraryItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control">
                    <option value="Book">Book</option>
                    <option value="DVD">DVD</option>
                    <option value="Audio Book">Audio Book</option>
                    <option value="Reference Book">Reference Book</option>
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId">
                    <option value=""> Select</option></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
                @if (ViewData.ModelState.ContainsKey("UniqueTitle"))
                {
                    <span class="text-danger">@ViewData.ModelState["UniqueTitle"].Errors.First().ErrorMessage</span>
                }
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pages" class="control-label"></label>
                <input asp-for="Pages" class="form-control" required 
                    data-val-required="Pages must be between 1 and 10000." />
                <span asp-validation-for="Pages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RunTimeMinutes" class="control-label"></label>
                <input asp-for="RunTimeMinutes" class="form-control" required 
                    data-val-required="RunTimeMinutes must be between 1 and 10000." />
                <span asp-validation-for="RunTimeMinutes" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsBorrowable" /> @Html.DisplayNameFor(model => model.IsBorrowable)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="~/js/validateLibraryItem.js" asp-append-version="true"></script>
    <script src="~/js/resetValidationMessages.js" asp-append-version="true"></script>
}

EzLib/Views/LibraryItems/Index.cshtml
@model IEnumerable<EzLib.Models.LibraryItem>

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center mb-5">Library Items</h1>

<div class="d-flex justify-content-between align-items-center mb-3">
    <h2>Items List</h2>
    <a class="btn btn-primary" asp-action="Create">Create New</a>
</div>

@*<form asp-controller="LibraryItems" asp-action="Index" method="get">
    <div class="form-row">
        <div class="col">
            <input type="text" name="searchString" class="form-control" placeholder="Search by title" />
        </div>
        <div class="col">
            <button type="submit" class="btn btn-primary">Search</button>
        </div>
    </div>
</form>*@

<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Author)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Pages)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RunTimeMinutes)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsBorrowable)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Borrower)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BorrowDate)
                </th>
                <th>
                    <a class="text-dark" asp-action="Index" asp-route-sortByType="Type">
                        @Html.DisplayNameFor(model => model.Type)
                    </a>
                </th>
                <th>
                    <a class="text-dark" asp-action="Index" asp-route-sortByType="Category">
                        @Html.DisplayNameFor(model => model.Category)
                    </a>
                </th>
                <th></th>
            </tr>
        </thead>
<tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pages)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RunTimeMinutes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsBorrowable)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Borrower)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BorrowDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.CategoryName)
            </td>
            <td class="text-end">
                <div class="btn-group btn-group-sm">
                    @if (item.IsBorrowable && string.IsNullOrEmpty(item.Borrower) && item.Type != "Reference Book")
                    {
                        <a class="btn btn-primary" asp-controller="BorrowReturnLibraryItem" asp-action="Borrow" asp-route-id="@item.Id">Borrow</a>
                    }
                    @if (!item.IsBorrowable && !string.IsNullOrEmpty(item.Borrower) && item.Type != "Reference Book")
                    {
                        <a class="btn btn-primary" asp-controller="BorrowReturnLibraryItem" asp-action="Return" asp-route-id="@item.Id">Return</a>
                    }
                    @if (item.IsBorrowable && string.IsNullOrEmpty(item.Borrower) || item.Type == "Reference Book")
                    {
                        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    }
                    <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.Id">Details</a>
                    @if (item.IsBorrowable && string.IsNullOrEmpty(item.Borrower) || item.Type == "Reference Book")
                    {
                        <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    }
                </div>
            </td>
        </tr>
}
</tbody>

</table>